# Generated by Django 4.1.5 on 2023-01-19 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_eventgroup_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='members',
            field=models.ManyToManyField(related_name='member_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
