# Generated by Django 4.1.5 on 2023-02-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgroup',
            old_name='opinion',
            new_name='opinions',
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='image',
            field=models.ImageField(default='../event_thumbline_yw77uq', upload_to='images/'),
        ),
    ]
