# Generated by Django 4.1.5 on 2023-02-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgroup',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterModelOptions(
            name='eventopinion',
            options={'ordering': ['-date_created']},
        ),
    ]
