# Generated by Django 4.1.5 on 2023-01-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=80, unique=True, verbose_name='Phone Number'),
        ),
    ]
